language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.5
          env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
    - composer self-update
    - composer --version
    - wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer.phar
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-cs-fixer.phar --version; fi

install:
    - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-source $COMPOSER_FLAGS

script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php php-cs-fixer.phar fix --dry-run -v; fi
    - bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then php bin/coveralls -v; fi
